plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

group = 'me.MrGraycat'
version = '3.0.0-SNAPSHOT'

sourceCompatibility = '17'
targetCompatibility = '17'

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
    maven { url 'https://papermc.io' }
    maven { url 'https://spigotmc.org' }
    maven { url 'https://extendedclip.com' }
    maven { url 'https://citizensnpcs.co' }
    maven { url 'https://viaversion.com' }
    maven { url 'https://md-5.net' }
}

dependencies {
    compileOnly 'org.spigotmc:spigot-api:1.20.1-R0.1-SNAPSHOT'
    compileOnly 'com.github.NEZNAMY:TAB:3.1.0'
    compileOnly 'net.citizensnpcs:citizens-main:2.0.30-SNAPSHOT'
    compileOnly 'me.clip:placeholderapi:2.11.2'
    compileOnly 'com.viaversion:viaversion-api:4.5.1'
    compileOnly 'LibsDisguises:LibsDisguises:10.0.31'
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}
